name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        env:
          LOGGER_LEVEL: ${{ secrets.LOGGER_LEVEL }}
          PORT: ${{ secrets.PORT }}
        run: docker compose build habit-loop-production

      - name: Create docker tag
        run: docker tag habit-loop-backend-habit-loop-production erickneitor/habit-loop-production

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/habit-loop-production

      - name: delete Kubernetes secret
        run: kubectl delete secret db-secret

      - name: Create Kubernetes secret
        run: kubectl create secret generic db-secret `
          --from-literal=DATABASE_URL=${{ secrets.DATABASE_URL }} `
          --from-literal=JWT_SECRET=${{ secrets.JWT_SECRET }} `
          --from-literal=DIRECT_URL=${{ secrets.DIRECT_URL }}

      - name: Deploy to miniKube
        run: kubectl apply -f .\infrastructure/
