name: CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        env:
          LOGGER_LEVEL: ${{ secrets.LOGGER_LEVEL }}
          PORT: ${{ secrets.PORT }}
        run: docker compose up -d --build habit-loop-production

      - name: Push Docker image
        run: docker push habit-loop-production
        
      - name: Deploy to miniKube
        run: kubectl apply -f .\infrastructure/
